---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myangapp
  name: myangapp
  namespace: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myangapp
  template:
    metadata:
      labels:
        app: myangapp
    spec:
      containers:
        #- image: 192.168.174.130:32684/angular-webapp:<TAG>
        - image: 192.168.136.131:32684/angular-webapp:<TAG>
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
          imagePullPolicy: Always
          name: myangapp
      imagePullSecrets:
      - name: registry-regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myangapp
  name: myangapp
  namespace: angular
spec:
  ports:
    - nodePort: 32233
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: myangapp
  type: NodePort
